### ISSUE TITLE
Vorschlag: questions_images.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/data-specification#12]
## Datei: questions_images.csv

Die Datei `questions_images.csv` soll folgende Spalten enthalten:

study, instrument, question, image_url, image_url_de, image_label, image_label_de

### Beispiel

study| instrument| question| image_url| image_url_de| image_label| image_label_de
| --- | --- | --- | --- | --- | --- | --- | 
soep-test | soep-test-2001-ah | income  | https://commons.wikimedia.org/wiki/Category:Income#/media/File:Classical_aggregate_expenditure.png  | https://commons.wikimedia.org/wiki/Category:Income#/media/File:Entscheidung_%C3%BCber_die_Erwerbsbeteiligung.jpg  | Something with income  | Etwas mit Einkommen  |

### Regel-Vorschlag

```yaml
schema:
  fields:
    - name: study
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: instrument
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: question
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: image_url
      type: string
      format: uri

    - name: image_url_de
      type: string
      format: uri

    - name: image_label
      type: string
      format: default
      constraints:
        maxLength: 40

    - name: image_label_de
      type: string
      format: default
      constraints:
        maxLength: 40

  primaryKey:
    - study
    - instrument
    - question
    - image_url
    - image_url_de
    - image_label
    - image_label_de
```
