### ISSUE TITLE
Vorschlag: attachments.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/data-specification#13]
## Datei: attachments.csv

Die Datei `attachments.csv` soll folgende Spalten enthalten:

type, study, dataset, variable, instrument, question, url,	url_text

### Beispiel

type| study| dataset| variable| instrument| question| url|	url_text
| ---  | --- | --- | --- | --- | --- | --- | --- | 
| study | soep-core | | | |  | https://doi.org/10.5684/soep.v34 | doi:10.5684/soep.v34  | 
| dataset | soep-core | bgpgen | | | | https://www.diw.de/documents/publikationen/73/diw_01.c.581299.de/diw_ssp0483.pdf | SOEP-Core v33.1 – Documentationof Person-related Status and Generated Variables in $PGEN
variable	| soep-core| 	bhp| 	bhp_52_kldb2010 | 			| | http://panel.gsoep.de/soep-docs/surveypapers/diw_ssp0470.pdf	| Informations on Occupational Coding
instrument | 	soep-core | 			| | soep-core-2017-hh		|| https://www.diw.de/documents/dokumentenarchiv/17/diw_01.c.611290.de/diw_ssp0563.pdf	| Print Version (de/en)

### Regel-Vorschlag

```yaml
schema:
  fields:
    - name: type
      title: Type of the Attachment
      type: string
      format: default
      constraints:
        required: true
        enum:
          - study
          - dataset
          - variable
          - instrument
          - question

    - name: study
      title: Foreign key to Study
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: dataset
      title: Foreign key to Dataset
      type: string
      format: default
      constraints:
        maxLength: 255

    - name: variable
      title: Foreign key to Variable
      type: string
      format: default
      constraints:
        maxLength: 255

    - name: instrument
      title: Foreign key to Instrument
      type: string
      format: default
      constraints:
        maxLength: 255

    - name: question
      title: Foreign key to Question
      type: string
      format: default
      constraints:
        maxLength: 255

    - name: url
      type: string
      format: uri
      constraints:
        required: true
        maxLength: 255

    - name: url_text
      type: string
      format: default
      constraints:
        required: true
        maxLength: 40

  primaryKey:
    - study
    - dataset
    - variable
    - instrument
    - question
    - url
    - url_text
```

Type muss in 
    - study
    - dataset
    - variable
    - instrument
    - question
enthalten sein.

Alle Spalten sind zuammen der Primary key -> keine Duplikate in der Tabelle erlaubt.
