### ISSUE TITLE
Vorschlag: answers.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/data-specification#14]
## Datei: answers.csv

Die Datei `answers.csv` soll folgende Spalten enthalten:

study,questionnaire,answer_list,value,label,label_de
oder
study,instrument,answer_list,value,label,label_de

### Beispiel

study | questionnaire / instrument | answer_list | value | label | label_de | 
| --- | --- | --- | --- | --- | --- | 
soep-core | soep-core-2017-e1 | 1+ | 1 | Yes | Ja

### Regel-Vorschlag

```yaml
schema:
  fields:
    - name: study
      title: Foreign key to Study
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: instrument
      title: Foreign key to Instrument
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: answer_list
      type: string
      format: default

    - name: value
      type: string
      format: default

    - name: label
      title: Label of the Answer (English)
      type: string
      format: default

    - name: label_de
      title: Label of the Answer (German)
      type: string
      format: default
```
