### ISSUE TITLE
Vorschlag: concepts.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/data-specification#15]
## Datei: concepts.csv

Die Datei `concepts.csv` soll folgende Spalten enthalten:

name, label, label_de, study, topic

### Beispiel

| name | label | label_de | study | topic
| --- | --- | --- | --- | --- | 
_100_p_tim | beruf,lehre,nebenerw. std., so |  hours sunday job, training | soep-core | tim

### Regel-Vorschlag

```yaml
schema:
  fields:
    - name: name
      title: Name of the Concept
      description: >-
        The name of the concept is used as the primary key in this table.
        It is imported into the database and search engine.
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: label
      title: Label of the Concept (English)
      type: string
      format: default

    - name: label_de
      title: Label of the Concept (German)
      type: string
      format: default

    - name: study
      title: Foreign key to Study
      type: string
      format: default

    - name: topic
      title: Foreign key to Topic
      type: string
      format: default

  primaryKey:
    - name
```

Konzepte sind zur Zeit studienübergreifend, da jedoch eine Verknüpfung zu Topics hergestellt werden kann / soll, welche wiederum studienspezifisch sind, muss ein Topic gemeinsam mit einer Studie referenziert werden.
