### ISSUE TITLE
Vorschlag: datasets.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/data-specification#16]
## Datei: datasets.csv

Die Datei `datasets.csv` soll folgende Spalten enthalten:

study, name, label, label_de, description, description_de, analysis_unit, conceptual_dataset, period

### Beispiel

study | name | label | label_de | description | description_de | analysis_unit | conceptual_dataset | period
| --- | --- | --- | --- | --- | --- | --- | --- | --- | 
soep-core | ah | Household questionnaire  |  | | | h | raw-org/net | 1984 |

### Regel-Vorschlag

```yaml
schema:
  fields:
    - name: study
      title: Foreign key to Study
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: name
      title: Name of the Dataset
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: label
      title: Label of the Dataset (English)
      type: string
      format: default

    - name: label_de
      title: Label of the Dataset (German)
      type: string
      format: default

    - name: description
      title: Description of the Dataset (Markdown, English)
      type: string
      format: default

    - name: description_de
      title: Description of the Dataset (Markdown, German)
      type: string
      format: default

    - name: analysis_unit
      title: Foreign key to AnalysisUnit
      type: string
      format: default

    - name: conceptual_dataset
      title: Foreign key to ConceptualDataset
      type: string
      format: default

    - name: period
      title: Foreign key to Period
      type: string
      format: default

  primaryKey:
    - study
    - name
```
