### ISSUE TITLE
Vorschlag: questionnaires.csv / instruments.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/data-specification#20]
## Datei: questionnaires.csv / instruments.csv

Die Datei `instruments.csv` soll folgende Spalten enthalten:

study, name, label, label_de, description, description_de, analysis_unit, period

### Beispiel

study | name | label | label_de | description | description_de | analysis_unit |  period
| --- | --- | --- | --- | --- | --- | --- | --- |
soep-core | soep-core-2017-e1 | Mother and Child (Newborns) 2017  | Mutter und Kind (Neugeborene) 2017  | | | h |  2017 |

### Regel-Vorschlag

```yaml
schema:
  fields:
    - name: study
      title: Foreign key to Study
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: name
      title: Name of the Instrument
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: label
      title: Label of the Instrument (English)
      type: string
      format: default

    - name: label_de
      title: Label of the Instrument (German)
      type: string
      format: default

    - name: description
      title: Description of the Instrument (Markdown, English)
      type: string
      format: default

    - name: description_de
      title: Description of the Instrument (Markdown, German)
      type: string
      format: default

    - name: analysis_unit
      title: Foreign key to AnalysisUnit
      type: string
      format: default

    - name: period
      title: Foreign key to Period
      type: string
      format: default

  primaryKey:
    - study
    - name
```
