### ISSUE TITLE
Vorschlag: periods.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/data-specification#5]
## Datei: periods.csv

Die Datei `periods.csv` soll folgende Spalten enthalten:

study,name,label,label_de,description,description_de

### Beispiel

study | name | label | label_de | description | description_de 
| --- | --- | --- | --- | --- | --- | 
soep-core | 1984 | 1984 | 1984 |  description |  description_de

### Regel-Vorschlag

siehe:
https://github.com/paneldata/data-specification/blob/e25b941b222e68592ebe61d4dac003dc2b0e1153/ddionrails_datapackage/datapackage/resources/periods.yml#L1-L71

**Comment by kwenzig** [comment]
Here are some aded descriptions and I started describing the behaviour of periods within the facetted search.

```YAML
schema:
  fields:
    - name: study
      title: Foreign key to Study
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: name
      title: Name of the Period
      description: >-      
          It is used in the facetted search and the tables for questionnaires and datasets.
          In the facetted search, the list of periods of all studies is unique by name.
          Period is a foreign key in questionnaires and datasets. 
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: label
      title: Label of the Period (English)
      description: >-      
          This label is displayed where period is used in the english UI.
      type: string
      format: default

    - name: label_de
      title: Label of the Period (German)
      description: >-      
          Not used at the moment. This label will be displayed where period is used in the german UI.
      type: string
      format: default

    - name: description
      title: Description of the Period (Markdown, English)
      description: >-      
          Not used at the moment.
      type: string
      format: default

    - name: description_de
      title: Description of the Period (Markdown, German)
      description: >-      
          Not used at the moment.
      type: string
      format: default

  primaryKey:
    - study
    - name
```
