### ISSUE TITLE
Vorschlag: conceptual_datasets.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/data-specification#7]
## Datei: conceptual_datasets.csv

Die Datei `conceptual_datasets.csv` soll folgende Spalten enthalten:

name, label, label_de, description, description_de

### Beispiel

study | name | label | label_de | description | description_de
| ---  | --- | --- | --- | --- | --- | 
soep-core | track | Tracking | Struktur-/Pfad-Daten | 	Essential files to track persons or household over time | 

### Regel-Vorschlag

```yaml
schema:
  fields:

    - name: study
      title: Foreign key to Study
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: name
      title: Name of the conceptual dataset
      type: string
      format: default
      constraints:
        required: true
        maxLength: 255

    - name: label
      title: Label of the conceptual dataset (English)
      type: string
      format: default

    - name: label_de
      title: Label of the conceptual dataset (German)
      type: string
      format: default

    - name: description
      title: Description of the conceptual dataset (Markdown, English)
      type: string
      format: default

    - name: description_de
      title: Description of the conceptual dataset (Markdown, German)
      type: string
      format: default

  primaryKey:
    - study
    - name
```
